export const ROOT_HEADER = document.getElementById('header')
export const ROOT_SCHEDULE = document.getElementById ('schedule')
export const ROOT_AUTH = document.getElementById ('auth')
export const ROOT_WORKS = document.getElementById ('works')
export const ROOT_ABOUT = document.getElementById ('about')
export const ROOT_REVIEW = document.getElementById ('review')
export const ROOT_ALL_PRODUCTS = document.getElementById ('all-products')
export const ROOT_STASH = document.getElementById('stash')